---
version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    command: --web.enable-lifecycle
    ports:
      - "9090:9090"
    volumes:
      - "/mnt/c/Users/piotr/workspace/masters-configs/monitoring/prometheus:/prometheus"

  grafana:
    image: grafana/grafana-enterprise:8.5.0
    container_name: grafana
    ports:
      - "9091:3000"
    depends_on:
      - prometheus
    volumes:
      - "/mnt/c/Users/piotr/workspace/masters-configs/monitoring/grafana:/var/lib/grafana"

networks:
  default:
    external:
      name: cluster-network-1