---
version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9.17
    container_name: rabbitmq
    ports:
      - "9095:5672" # rabbitmq
      - "9002:15692" # metrics
      - "9092:15672" # management
    volumes:
      - "/mnt/c/Users/piotr/workspace/masters-configs/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    restart: always
  
networks:
  default:
    external:
      name: cluster-network-1
    
